### ISSUE TITLE
Differentiated Care Line list.

### ISSUE THREAD

**Issue by thnesh** [chap-uzima/IQTools#11]
Could we have the Line list of those who meet the criteria (Stable Patients) in IQTools if possible at the homepage, if not as part of the queries

**Comment by chris-githu** [comment]
@thnesh Please define a patient who meets the criteria of _Stable_ here for reference. Also indicate what can be extracted or not from IQCare.

Thanks.

**Comment by jmbula** [comment]
@chris-githu  just to follow up on the query from @thnesh  below see the definitions for stable vs unstable
![image](https://user-images.githubusercontent.com/34089749/33832468-5ad5b92a-de8d-11e7-9616-2701076cbc54.png)
[DCM -Stable- Unstabe.pptx](https://github.com/chap-uzima/IQTools/files/1547853/DCM.-Stable-.Unstabe.pptx)

**Comment by chris-githu** [comment]
Hi @jmbula 
Please see below what we can extract from the EMR including my opinion of level of accuracy for eac


Parameter | Availability in IQCare
-- | --
On Current Regimen for >= 12 months | Yes.. Can determine with high accuracy
No Active OIs | Yes.. Mid accuracy
Adherent to Scheduled Clinic Visits | Yes.. Mid accuracy
<1000 copies/ml Last Viral Load | Yes.. High accuracy
Completed 6 months of IPT | Yes.. Mid accuracy
Non-pregnant/Not breastfeeding | Yes.. Low accuracy
BMI >= 18.5 | Yes.. High Accuracy
Age >= 20 years | Yes.. High Accuracy
Healthcare team approval | No.. Not documented

Taking this into account, do we still want to automate this list?
How do we plan to use it at the site?

**Comment by jmbula** [comment]
Hi Chris, I think we can have the function automated on IQtools for future use especially after improved and consistent updating of patient level records in IQcare. But as of now I  think we will have to do this categorization using the manual check list due to the  non-optimal documentation of these parameters in IQcare.

**Comment by chris-githu** [comment]
@jmbula I tend to agree with this. Also, I am still not convinced about the utility of a line list of _All Stable Patients_. How would this be helpful? The status _Stable_ or not is very fluid. Wouldn't this be more of an `IQCare` enhancement that shows on the patient dashboard whether they have been classified as stable?

Put simply, what would we do with this line list, even if we could generate it accurately?
@thnesh @mkaburu

**Comment by jmbula** [comment]
Yes, it will be good if the status can show at the patient dashboard.
However currently since we have very many facilities that are still doing
badly on DCM mainly because they have not been able to categorize their
patients a line list will help to fast track the activity but I agree with
you that patient status is not static and will keep on changing every now
and then for instance a female patient who was categorized as stable once
they get pregnant they will change to unstable- there should be a provision
to evaluate patients status at every by both the triage nurses and the
clinicians.
