### ISSUE TITLE
Care and Treatment Report

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQTools#7]
@chris-githu,please assist create Care and treatment monthly report.Query to be shared to facilities would also assist.
VL Instructions and report template are attached.Thanks.

![vl instructions](https://user-images.githubusercontent.com/31826771/33417952-ac314ece-d5b4-11e7-97ee-1b50f7da67e2.PNG)
[Care Treatment Program Report 2017 10 31.xlsx](https://github.com/chap-uzima/IQTools/files/1516805/Care.Treatment.Program.Report.2017.10.31.xlsx)

**Comment by jmbula** [comment]
@vogoti @chris-githu  I think this is related to the VL Cascade issue on CQI Template reports- the info needed is similar  - so a query and/or incorporation of this as one of the IQtools generated reports will sort us kabisa.

**Comment by thnesh** [comment]
Since we stopped using the HIV care and treatment Monthly report that currently in IQTools can we replace it with the current one??
[Care Treatment Program Monthly Reportinng Template.xlsx](https://github.com/chap-uzima/IQTools/files/1684603/Care.Treatment.Program.Monthly.Reportinng.Template.xlsx)
[Care and Treatment Children and Adolescents Monthly Reporting Template.xlsx](https://github.com/chap-uzima/IQTools/files/1684608/Care.and.Treatment.Children.and.Adolescents.Monthly.Reporting.Template.xlsx)

**Comment by chris-githu** [comment]
@vogoti @lmwaniki 
Please see below the proposed template for this report in IQTools.
The reference worksheet should contain clear indicator definitions, both from the requirements perspective and from an IQCare documentation perspective.

[CDC_Care_and_Treatment_Report_Template.xlsx](https://github.com/chap-uzima/IQTools/files/1706157/CDC_Care_and_Treatment_Report_Template.xlsx)

Let's discuss here if any of these are not clear.
We can include another worksheet that maps the results to the CDC format.

Thanks.

**Comment by lmwaniki** [comment]
Hi Chris,

Thanks for the new template it looks good. My only concern is 3PM is about to start and we plan possible updating at facility level, will the facility data managers be able to make the updates using the new queries? C&T format in 3PM is exactly as CDC report template.

**Comment by chris-githu** [comment]
@lmwaniki This template is what IQTools will generate, @vogoti will work on mapping it, via excel formulas, to the expected CDC format  within the same report.
We will also include line lists in the report as necessary.
Of importance now is clear definition of the indicators and how they translate to data in IQCare.
@vogoti Please start off that discussion here and copy anyone who can provide more information from your team.

Thanks.

**Comment by chris-githu** [comment]
**Eligible for VL**
- Does this include clients who were eligible at the beginning of the reporting period or at the end?
- Does it include clients who were eligible in previous reporting periods but had not gotten a VL order by the beginning of the reporting period?
- Does it include clients who are deemed eligible regardless of whether they got a VL ordered in the reporting month?

@lmwaniki @jmbula @vogoti

**Comment by vogoti** [comment]
@chris-githu ,taking a scenario that am reporting as of 31st October 2017 my Eligible would be;

- Any client who was eligible as of 1st Oct 2017(Start of the reporting period)

- A Client from a previous reporting period who has not received a VL

- Despite a client getting a VL ordered within the month they would still be counted as eligible since at the start of the period they did not have the VL.

- In my opinion at the start of the reporting period the following clients would be deemed eligible-All active clients on ART for more than 6 months with no VL,all active clients with a VL past 12 months,all active clients whose last VL>1000 and the VL is more than 3 months old

@lmwaniki @jmbula @thnesh @mkaburu @DMasese what are your thoughts?

**Comment by vogoti** [comment]
@dkemunto

**Comment by mkaburu** [comment]
@vogoti  I agree with all that. Is it possible to break it this way for easier interaction with the line list
•	Eligible for a 6 month VL(based on the ART start date)
•	Eligible for 12 month VL(based on the ART start date)
•	Eligible for an annual VL(based on the last VL date)
•	Pregnant or breastfeeding based on the their last VL i.e. if last VL> 6 months
•	Patients on ART for more than 12 months with last VL more than 12 months ago 
•	Patients on ART > 6 months without VL
@thnesh @chris-githu @jmbula @lmwaniki @DMasese @dkemunto

**Comment by chris-githu** [comment]
All.
Please see below draft eligibility definition. Let's try and hash this out.

![eligibility](https://user-images.githubusercontent.com/13725334/36086844-b380d4aa-0fdf-11e8-94d5-f449d65e89bc.PNG)

**Comment by dkemunto** [comment]
Hi all,
I am just trying to go back to the definition for the 'Eligible for VL' indicator as given in the Care and Treatment Monthly report.It misses out a whole lot of individuals looking at the criteria Matthew has listed above (which is correct-for the clients who are normally considered eligible for VL'

Have we been including all those categories when reporting this data or just those who have been on treatment for at least 12 months and are eligible for VL in the reporting month?

@vogoti @thnesh @lmwaniki @mkaburu

**Comment by chris-githu** [comment]
@dkemunto I'll let the rest of the team answer that question since I have heard all sorts of differing opinions on who should be counted as eligible.

A few more clarifications...
- This might be obvious but just so that we are on the same page, LDL results are a subset of < 1000, Yes?
- We need to check how sites are recording LDL results. The databases show results ranging from 0 to 50, free text results like 'undetectable' sometimes mispelt. Since all of our sites are on version 4+, let's ensure that LDL results are captured uniformly.
- Second VL - Is this meant to count orders (samples collected) for a repeat VL or just results received after a repeat VL? The template is not explicit.

Thanks.

**Comment by vogoti** [comment]
@dkemunto in my opinion the 'Eligible VL' indicator has not been considering all those scenarios,what is mainly looked at is clients who have been on ART for more than 6 months without a VL and clients due for an annual VL in that reporting month without considering clients who mightnot have had their annual VLs in preceding months and are still pending
@jmbula @thnesh @mkaburu @lmwaniki @jkarigi @pgitonga @irenefaith @chris-githu

**Comment by dkemunto** [comment]
@vogoti That is okay and I think based on the template,that is the data it was looking for.(Although now for CQI purposes,we know we have very many other clients who would qualify to be eligible for VL).
For the 'Second VL Done' what have we been collecting? Samples collected or Results received? @thnesh @mkaburu @jkarigi 

@chris-githu , @lmwaniki shared some email from CDC,LDL should not be included under  the<1,000.

**Comment by jmbula** [comment]
Hi everyone,
I can see we have a long thread of discussion here regarding VL eligibility (for a quarterly report) for the annual  and  6 months VL  monitoring its fairly straight forward: any one or ART for more than 6/12 months and has not had a VL in the last 6/12 months respectively.

The issue comes in when we are trying to find those illegible in a reporting Quarter lets say OCT-DEC
I tend to agree with Mathew and Chris that for the uptake and suppression rates to be objective we have to factor in the different  eligibility criteria ( the first three bullets below since for Pregnant and breast feeding its the same criteria but to a special population)
 
•	Eligible for 12 month VL(based on the ART start date)
        Eligible for a 6 month VL(based on the ART start date)
•	Eligible for an annual VL(based on the last VL date)
•	Pregnant or breastfeeding based on the their last VL i.e. if last VL> 6 months
•	Patients on ART for more than 12 months with last VL more than 12 months ago
For the quarterly reports  I think we need to be presenting the three categories each as an entity
That is -Uptake and suppression rate at 6 months 
            -Uptake and Suppression rate at 12 months 
            -Annual (Routine) uptake  and Suppression rates
As we speak our uptake rate for Oct-Dec has come to 63% but I think its because both those  eligible  for 6 and 12 months VL have been lumped up together.

@vogoti @chris-githu  could you kindly see if there is a query that can help separate these two then going forward can we can think of factoring this  in  IQcare tools for the different reports.

I am still thinking about the criteria for getting those eligible for repeat VL from the system- currently we are trying to collect through the CQI report that is still not very reliable- @vogoti @chris-githu  again we will need your help in this.

@irenefaith @lmwaniki @mkaburu  @dkemunto

**Comment by dkemunto** [comment]
Hi all.
As for the criteria for getting those eligible for repeat VL,the guidelines recommend  that a repeat VL should be done for those who have high VL (>1,000) after 3 months of good adherence.The challenge is that it is not possible to determine when these 3 months of good adherence will be attained by the clients since there are various barriers that need to be addressed beforehand and also the delays we have before identifying high VL clients and taking action on them e.g.sending clients for EAC.

My suggestion-Adopt 4 months as the approximate period within which a repeat VL for a high VL should have been done.This will cater for that delay between identification and action and give time for clients to try and institute 'corrective' measures on adherence so that they can have 3 months of good adherence before their next VL.
@jmbula

**Comment by irenefaith** [comment]
Hi Everyone, I have not been getting discussions on GitHub but now am fully inhouse.

**Comment by irenefaith** [comment]
@dkemunto  your suggestion makes alot of sense but will we be adhering to the guidelines if we do 4 months instead of 3 months? My suggestion is also if we go by 4 months then this should be properly documented and probably have it shared and infact have an SOP guiding on the same thing.
@jmbula  and @dkemunto  as we conclude this issue of VL can we have a program SOP on the same that will also be shared with facilities.

**Comment by ekibunyi** [comment]
@dkemunto it should be 3 months complete otherwise if we say 4 months in practise this can be pushed to 5 and so on. 
is it possible to tie this VLs to the cohorts so that we can measure as such? the confusion came in when we rolled VL testing and can we define them the way we did previously for CD4 testing i.e 1 month before and 2 months. this is in anticipation for reporting on cohorts by suppression and retention. already CDC is asking for maternal cohort suppression and retention.

i'm glad niko ndani.

**Comment by irenefaith** [comment]
@ekibunyi I agree with you 100%.
@dkemunto @jmbula @vogoti

**Comment by chris-githu** [comment]
Hi All.
@ekibunyi Welcome :-)
We already have VL by 12 month cohort in the MoH731 report as shown below.
![12mcohort](https://user-images.githubusercontent.com/13725334/36366176-fce26e8c-155d-11e8-8582-51a635e74dbe.PNG)

And already working on the a Maternal Cohort Analysis report.

All. We have already released a test version of the Care and Treatment Report in v4.0.0.1. I would suggest we take some time this week to review the output from multiple sites to identify any gaps in the reporting logic as well as IQCare documentation before roll-out next week.

Thanks.

**Comment by vogoti** [comment]
@mkaburu @thnesh @snyachae @lmwaniki @pgitonga @jkarigi The link for v4.0.0.1;
[https://iqtools.azurewebsites.net/apps/iqtools/beta/IQTools.Application](url)

Test the Care and treatment report with some of your facility DBs and provide feedback

**Comment by mkaburu** [comment]
@chris-githu  on the Care and treatment report, samples collected- is this data being picked from a lab form created in the reporting month with or without results?

**Comment by chris-githu** [comment]
@vogoti Please liaise with your team to test this report.
We are quite overdue with the v4.1 milestone.
I am going to consider this report ready for release and we can handle any issues in 4.1.x - 4.2.

I will go ahead and close this. Please open new issues, specific to the concern raised.

Thanks
